AllCops:
  TargetRubyVersion: 2.4
Rails:
  Enabled: true
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/LineLength:
  Max: 100
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded